### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by wadexu007** [open-telemetry/opentelemetry-helm-charts#544] opened 2022-12-07 09:49 UTC
**Issue**:
panic: runtime error: invalid memory address or nil pointer dereference when hostMetrics enabled.

On **env**:
Chart version opentelemetry-collector-0.40.7
APP verison 0.66.0
GKE 1.22
Helm v3.5.0

Steps:
1. config.yaml
```
mode: daemonset

presets:
  hostMetrics:
    enabled: true

config:
  processors:
    memory_limiter:
      check_interval: 5s
      limit_mib: 1600
      spike_limit_mib: 500
```

2. `helm install otel-collector  open-telemetry/opentelemetry-collector -f config.yaml`
3. Pods `CrashLoopBackOff`
4. Check pod logs

```
2022-12-07T09:46:27.396Z	info	extensions/extensions.go:48	Extension started.	{"kind": "extension", "name": "health_check"}
2022-12-07T09:46:27.396Z	info	extensions/extensions.go:44	Extension is starting...	{"kind": "extension", "name": "memory_ballast"}
2022-12-07T09:46:27.399Z	info	service/service.go:115	Starting shutdown...
2022-12-07T09:46:27.399Z	info	healthcheck/handler.go:129	Health Check state change	{"kind": "extension", "name": "health_check", "status": "unavailable"}
2022-12-07T09:46:27.399Z	info	pipelines/pipelines.go:118	Stopping receivers...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x8d316d]

goroutine 1 [running]:
net/http.(*Server).Close(0x0)
	net/http/server.go:2732 +0x4d
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver.(*zipkinReceiver).Shutdown(0xc000c82240, {0x69619a1, 0x2})
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver@v0.66.0/trace_receiver.go:165 +0x25
go.opentelemetry.io/collector/service/internal/pipelines.(*Pipelines).ShutdownAll(0xc000c80e10, {0x75de9c0, 0xc0000c2018})
	go.opentelemetry.io/collector@v0.66.0/service/internal/pipelines/pipelines.go:121 +0x499
go.opentelemetry.io/collector/service.(*service).Shutdown(0xc000d54680, {0x75de9c0, 0xc0000c2018})
	go.opentelemetry.io/collector@v0.66.0/service/service.go:121 +0xd4
go.opentelemetry.io/collector/service.(*Collector).shutdownServiceAndTelemetry(0xc001277a88, {0x75de9c0?, 0xc0000c2018?})
	go.opentelemetry.io/collector@v0.66.0/service/collector.go:264 +0x36
go.opentelemetry.io/collector/service.(*Collector).setupConfigurationComponents(0xc001277a88, {0x75de9c0, 0xc0000c2018})
	go.opentelemetry.io/collector@v0.66.0/service/collector.go:166 +0x286
go.opentelemetry.io/collector/service.(*Collector).Run(0xc001277a88, {0x75de9c0, 0xc0000c2018})
	go.opentelemetry.io/collector@v0.66.0/service/collector.go:190 +0x46
go.opentelemetry.io/collector/service.NewCommand.func1(0xc000170900, {0x69107b9?, 0x1?, 0x1?})
	go.opentelemetry.io/collector@v0.66.0/service/command.go:53 +0x479
github.com/spf13/cobra.(*Command).execute(0xc000170900, {0xc0000b4030, 0x1, 0x1})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000170900)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
main.runInteractive({{0xc000550cc0, 0xc000551e90, 0xc0005510e0, 0xc000550960}, {{0x69388ae, 0xf}, {0x69b56ff, 0x1f}, {0x690a299, 0x6}}, ...})
	github.com/open-telemetry/opentelemetry-collector-releases/contrib/main.go:32 +0x5d
main.run(...)
	github.com/open-telemetry/opentelemetry-collector-releases/contrib/main_others.go:11
main.main()
	github.com/open-telemetry/opentelemetry-collector-releases/contrib/main.go:25 +0x1d8
```

Anyone can help for this issue?

Thank you.

**Comment by TylerHelmuth** [comment] 2022-12-07 15:47
@wadexu007 I was unable to reproduce this issue with your values.yaml and chart version.  It looks like the collector is shutting down during its startup sequence which is causing some issues with the Zipkin receivers shutdown processes, but I think that is unrelated.  The real problem is that shutdown is starting while the extensions are being started up.

My initial guess is that there is another permission issue somewhere with the collector and your cluster.  Or maybe something with k8s 1.22.  What happens if you try a more recent k8s version?

**Comment by wadexu007** [comment] 2022-12-08 08:27
@TylerHelmuth Thanks for point me it related to extensions. 

```
  extensions:
    memory_ballast:
      size_in_percentage: 40
```
I think this default extensions memory_ballast config caused my pod error
```
Error: failed to start extensions: open /hostfs/var/lib/docker/overlay2/1e58c5b6f2e5d08595852d0d2e04a5e0cbed025c445097ed2201501e3b789c18/merged/sys/fs/cgroup/memory/memory.limit_in_bytes: permission denied; failed to shutdown service after error: failed to shutdown pipelines: no existing monitoring routine is running
```

Now, my workaround is explicitly declare extension only use health_check. Then my pods running well.

```
mode: daemonset

presets:
  hostMetrics:
    enabled: true

config:
  processors:
    memory_limiter:
      check_interval: 5s
      limit_mib: 1600
      spike_limit_mib: 500

  service:
    extensions:
    - health_check
```

**Comment by TylerHelmuth** [comment] 2022-12-08 15:27
@wadexu007 that error message looks like the same as the permission issue you are having with memory_limiter.  Can we close this issue and track everything in https://github.com/open-telemetry/opentelemetry-helm-charts/issues/543?

**Comment by wadexu007** [comment] 2022-12-09 01:55
@TylerHelmuth Sure, please go ahead.

**Closed** 2022-12-09 02:25 UTC
Labels: bug, chart:collector
