### ISSUE TITLE
IMAGEPULLBACK error due to missing ImagePullSecrets on POD private registry image

### ISSUE THREAD

**Issue by sreejesh-radhakrishnan-db** [open-telemetry/opentelemetry-helm-charts#781] opened 2023-05-10 12:48 UTC
Hello,
I am following https://opentelemetry.io/docs/k8s-operator/automatic/#create-an-opentelemetry-collector-optional and my deployment is failing for IMAGEPULL error . as its private reg for image.

I have seen a similar issue https://github.com/open-telemetry/opentelemetry-helm-charts/issues/696 : since NO update  I am creating new one.  really appreciate if someone can update on next step. as currently I am blocked. 

Update on original ticket:
The helm chart now allows imagePullSecrets for the operator image, but this doesn't fall into the collector (unless I am missing something).

Perhaps it would be easier to add them to the service accounts if set in .Values.imagePullSecrets

**Comment by TylerHelmuth** [comment] 2023-05-10 14:35
@sreejesh-radhakrishnan-db thanks for raising this issue to our attention again.  Since this is a duplicate of https://github.com/open-telemetry/opentelemetry-helm-charts/issues/696 I am going to close this issue and respond over there.

**Closed by TylerHelmuth** 2023-05-10 14:35 UTC
