### ISSUE TITLE
Update release lifecycle to support Conventional Commit, Release Please and automatic CHANGELOG

### ISSUE THREAD

**Issue by pragmaticivan** [open-telemetry/opentelemetry-helm-charts#78] opened 2021-09-15 19:21 UTC
For ref: https://github.com/google-github-actions/release-please-action

**Comment by jvoravong** [comment] 2023-10-11 21:25
Hi @TylerHelmuth,

I've noticed a discrepancy in the release notes under [opentelemetry-collector-0.72.0](https://github.com/open-telemetry/opentelemetry-helm-charts/releases/tag/opentelemetry-collector-0.72.0). The content states "Full Changelog: [opentelemetry-operator-0.39.2...opentelemetry-collector-0.72.0](https://github.com/open-telemetry/opentelemetry-helm-charts/compare/opentelemetry-operator-0.39.2...opentelemetry-collector-0.72.0)" and mentions both the operator and collector charts. Typically, release notes are specific to one project. Is this expected? I suspect something might be slightly off.

Side Note: I'm working on a collector chart distro project and adding a similar feature to support an ongoing CHANGELOG and release notes feature ([#923](https://github.com/signalfx/splunk-otel-collector-chart/pull/923)). We would like to invest, help develop, and adopt the functionality in this project where possible so we can incorporate it into our distro. We can create or follow new GH issues as needed.

Thank you!

**Comment by TylerHelmuth** [comment] 2023-10-11 21:39
@jvoravong Good catch, I was not expecting that behavior. I will reopen this issue and investigate more tomorrow.

**Comment by TylerHelmuth** [comment] 2023-10-12 14:33
Looking into this, the expected behavior for the github action is to generate "Full Changelog: [opentelemetry-operator-0.39.2...opentelemetry-collector-0.72.0](https://github.com/open-telemetry/opentelemetry-helm-charts/compare/opentelemetry-operator-0.39.2...opentelemetry-collector-0.72.0)" since that is the exact changes between releases.  The same behavior is happening in the prometheus helm chart repo: https://github.com/prometheus-community/helm-charts/releases/tag/kube-prometheus-stack-51.3.0.  Since every chart change is a release, comparing the differences between releases will always be an accurate way to show the files that changed for the release.

I am curious about using `chloggen`, but I view that as a potential improvement.  I am going to close this issue again, but please open a new issue if you'd like to continue the discussion of how to incorporate `chloggen` for the 3 charts.

**Closed by TylerHelmuth** 2023-10-12 14:33 UTC
Labels: help wanted
